### ISSUE TITLE
Program to sort an array in ascending order....

### ISSUE THREAD

**Issue by rahulkumar6142998** [Hacktoberfest-2021/Basic_Programming#1]
Example :
Input :  A = [2,5,3,6,,1,4]
Output: =[1,2,3,4,5,6]

**Comment by ssurbhi09** [comment]
Can you please assign me

**Comment by anupriya-21** [comment]
@rahulkumar6142998  I want to solve this problem

**Comment by rahulkumar6142998** [comment]
@ssurbhi09  Yes

**Comment by ssurbhi09** [comment]
i have done pls see and then any issue pls let me inform

**Comment by ssurbhi09** [comment]
Is it fine or is that any issues?

**Comment by rahulkumar6142998** [comment]
@ssurbhi09  what is your a progress status?

**Comment by ssurbhi09** [comment]
I done

**Comment by RajeshSaha2001** [comment]
I want to solve this using cpp @rahulkumar6142998

**Comment by rahulkumar6142998** [comment]
@RajeshSaha2001 Okk go for it

**Comment by deep846** [comment]
> @deep846 I want to solve

Assigned

**Comment by ssurbhi09** [comment]
See my pr please

**Comment by sheetal2001p** [comment]
I want to solve it using Java @rahulkumar6142998 @deep846

**Comment by ssurbhi09** [comment]
See my pr #23
